# Generated by Django 3.0.6 on 2020-06-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adopciones',
        ),
        migrations.RemoveField(
            model_name='grado',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='apellido',
        ),
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='grado',
            name='nivel',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.alumno'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='grado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.grado'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='seccion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.seccion'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
